#!/usr/bin/env python3
"""Build the Gazebo world and the Nav2 map from the brain's own grid.

    python3 scripts/generate_world.py

Run this if you ever change the warehouse layout in
shared/fleetx_core/grid.py. Generating both from one source is the point: a
hand-drawn world would slowly stop matching the map the robots plan against,
and every robot would be confidently wrong about where the shelves are.

Produces:
    worlds/warehouse.world   for Gazebo
    maps/warehouse.pgm       for Nav2
    maps/warehouse.yaml      for Nav2
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
# ros2_ws/src/fleet_bringup/scripts -> repo root
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(HERE))))
sys.path.insert(0, os.path.join(REPO, "shared"))

from fleetx_core.grid import Cell, CellKind, default_grid   # noqa: E402

RESOLUTION = 1.0        # metres per grid square. Must match translate.py.
SHELF_HEIGHT = 1.6
WALL_HEIGHT = 1.0
PIXELS_PER_CELL = 10    # map resolution: 0.1 m per pixel


def world_xy(gx, gy):
    """Grid square -> Gazebo metres. y flips: the grid reads downward."""
    return gx * RESOLUTION, -gy * RESOLUTION


def box(name, gx, gy, height, rgba):
    x, y = world_xy(gx, gy)
    s = RESOLUTION * 0.96
    return f"""    <model name="{name}">
      <static>true</static>
      <pose>{x:.3f} {y:.3f} {height / 2:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{s:.3f} {s:.3f} {height:.3f}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{s:.3f} {s:.3f} {height:.3f}</size></box></geometry>
          <material><ambient>{rgba}</ambient><diffuse>{rgba}</diffuse></material>
        </visual>
      </link>
    </model>
"""


def marker(name, gx, gy, rgba):
    """A flat coloured tile. Robots drive over these -- they are destinations,
    not obstacles, so they have no collision geometry."""
    x, y = world_xy(gx, gy)
    s = RESOLUTION * 0.9
    return f"""    <model name="{name}">
      <static>true</static>
      <pose>{x:.3f} {y:.3f} 0.005 0 0 0</pose>
      <link name="link">
        <visual name="visual">
          <geometry><box><size>{s:.3f} {s:.3f} 0.01</size></box></geometry>
          <material><ambient>{rgba}</ambient><diffuse>{rgba}</diffuse></material>
        </visual>
      </link>
    </model>
"""


def build_world(grid):
    parts = ["""<?xml version="1.0"?>
<!-- GENERATED by fleet_bringup/scripts/generate_world.py -->
<!-- Do not edit by hand: edit shared/fleetx_core/grid.py and re-run it. -->
<sdf version="1.6">
  <world name="fleetx_warehouse">
    <include><uri>model://sun</uri></include>
    <include><uri>model://ground_plane</uri></include>

    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>

    <scene><ambient>0.6 0.6 0.6 1</ambient><shadows>false</shadows></scene>
"""]

    for gy in range(grid.height):
        for gx in range(grid.width):
            kind = grid.kind(Cell(gx, gy))
            if kind is CellKind.SHELF:
                parts.append(box(f"shelf_{gx}_{gy}", gx, gy, SHELF_HEIGHT,
                                 "0.25 0.28 0.33 1"))
            elif kind is CellKind.PICK:
                parts.append(marker(f"pick_{gx}_{gy}", gx, gy, "0.15 0.45 0.30 1"))
            elif kind is CellKind.DROP:
                parts.append(marker(f"drop_{gx}_{gy}", gx, gy, "0.10 0.35 0.50 1"))
            elif kind is CellKind.CHARGER:
                parts.append(marker(f"charger_{gx}_{gy}", gx, gy, "0.45 0.35 0.10 1"))

    # A wall right around the outside, so nothing wanders off the floor.
    for gx in range(-1, grid.width + 1):
        parts.append(box(f"wall_n_{gx}", gx, -1, WALL_HEIGHT, "0.18 0.20 0.24 1"))
        parts.append(box(f"wall_s_{gx}", gx, grid.height, WALL_HEIGHT, "0.18 0.20 0.24 1"))
    for gy in range(grid.height):
        parts.append(box(f"wall_w_{gy}", -1, gy, WALL_HEIGHT, "0.18 0.20 0.24 1"))
        parts.append(box(f"wall_e_{gy}", grid.width, gy, WALL_HEIGHT, "0.18 0.20 0.24 1"))

    parts.append("  </world>\n</sdf>\n")
    return "".join(parts)


def build_map(grid):
    """An occupancy grid for Nav2. Black = shelf, white = floor."""
    w = (grid.width + 2) * PIXELS_PER_CELL
    h = (grid.height + 2) * PIXELS_PER_CELL
    pixels = bytearray([254] * (w * h))     # 254 = free

    def paint(gx, gy, value):
        for py in range(PIXELS_PER_CELL):
            for px in range(PIXELS_PER_CELL):
                ix = (gx + 1) * PIXELS_PER_CELL + px
                iy = (gy + 1) * PIXELS_PER_CELL + py
                pixels[iy * w + ix] = value

    for gy in range(grid.height):
        for gx in range(grid.width):
            if grid.kind(Cell(gx, gy)) is CellKind.SHELF:
                paint(gx, gy, 0)            # 0 = occupied
    for gx in range(-1, grid.width + 1):
        paint(gx, -1, 0)
        paint(gx, grid.height, 0)
    for gy in range(grid.height):
        paint(-1, gy, 0)
        paint(grid.width, gy, 0)

    header = f"P5\n# GENERATED by generate_world.py\n{w} {h}\n255\n".encode()
    return header + bytes(pixels), w, h


def build_map_yaml(grid_height: int):
    metres_per_pixel = RESOLUTION / PIXELS_PER_CELL
    # The image's top-left pixel is grid (-1,-1) = world (-1, +1).
    origin_x = -1.5 * RESOLUTION
    origin_y = -(grid_height + 0.5) * RESOLUTION
    return f"""# GENERATED by fleet_bringup/scripts/generate_world.py
image: warehouse.pgm
resolution: {metres_per_pixel}
origin: [{origin_x}, {origin_y}, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196
"""


if __name__ == "__main__":
    grid = default_grid()

    world_path = os.path.join(PKG, "worlds", "warehouse.world")
    with open(world_path, "w") as fh:
        fh.write(build_world(grid))

    pgm, w, h = build_map(grid)
    with open(os.path.join(PKG, "maps", "warehouse.pgm"), "wb") as fh:
        fh.write(pgm)
    with open(os.path.join(PKG, "maps", "warehouse.yaml"), "w") as fh:
        fh.write(build_map_yaml(grid.height))

    print(f"  world : {world_path}")
    print(f"  map   : {w}x{h} pixels, {grid.width}x{grid.height} squares")
    print("  Re-run this whenever shared/fleetx_core/grid.py changes.")
